blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/<slug:post_slug>/", views.detail, name="detail"),
    path("category/<slug:cat_slug>/", views.category, name="category"),
    path("tag/<slug:tag_slug>/", views.tag, name="tag"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("search/", views.search, name="search"),

    path("robots.txt", views.robots, name="robots"),
    path("ads.txt", views.ads, name="ads"),
]

realcoder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap, StaticViewSitemap, CategorySitemap


sitemaps = {
    'static': StaticViewSitemap,
    'post': PostSitemap,
    'category': CategorySitemap,
}

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("email-list/", include("marketing.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone


# Author model
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


# Category model
class Category(models.Model):
    tag = models.CharField(max_length=50, unique=True)
    slug = models.SlugField()
    meta_description = models.TextField(max_length=170, blank=True)

    def __str__(self):
        return f'{self.tag}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:category', args=[str(self.slug)])


class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)
    slug = models.SlugField()
    popular = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.tag}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:tag', args=[str(self.slug)])


# Post model
class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='post_images', blank=True)
    meta_description = models.TextField(max_length=170, blank=True)
    content = RichTextUploadingField()
    pub_date = models.DateTimeField(default=timezone.now)      # default=timezone.now - from django.utils import tim...
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="posts")
    featured = models.BooleanField(default=False)
    popular = models.BooleanField(default=False)


    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:detail', args=[str(self.slug)])


# Comment model
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=99)
    email = models.EmailField()
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment on ''{self.post}'' by {self.name}"


# Comment Reply
class ReplyComment(models.Model):
    name = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies", blank=False)
    reply_message = models.TextField(blank=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"Reply: {self.reply_message}"


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(blank=False)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message: {self.name} - {self.message[:150]}..."

blog/forms.py
from django import forms
from .models import Comment, Contact


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'name', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

blog/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q
from .forms import *
from django.contrib import messages
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage


# Create your views here.

# global stuff
popular_posts = Post.objects.filter(popular=True, featured=True)
categories = Category.objects.all()
tags = Tag.objects.filter(popular=True)


def index(request):
    posts = Post.objects.filter(featured=True)

    # Pagination - My most impressive implementation
    paginator = Paginator(posts, 3)
    num_pages = [i for i in range(1, paginator.num_pages)]
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        post_list = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver last page of results
        post_list = paginator.page(paginator.num_pages)

    context = {
        "posts": post_list,
        "num_pages": num_pages,

        "popular_tags": tags,
        "popular_posts": popular_posts,
        "categories": categories,
    }
    return render(request, "blog/index.html", context)


def detail(request, post_slug):
    post = Post.objects.get(slug=post_slug)
    comments = post.comments.filter(active=True)
    post_tags = post.tags.all()

    new_comment = None
    # comment posted
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Create a comment but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            messages.success(request, "Your comment is awaiting moderation.")
    else:
        comment_form = CommentForm()


    context = {
        "post": post,
        "comments": comments,
        "post_tags": post_tags,
        "new_comment": new_comment,
        # sidebars
        "categories": categories,
        "popular_posts": popular_posts,
        "popular_tags": tags,
    }
    return render(request, "blog/detail.html", context)


def category(request, cat_slug):
    cat = Category.objects.get(slug=cat_slug)
    posts = cat.posts.filter(featured=True)

    context = {
        "posts": posts,
        "category": cat,

        # sidebar
        "popular_posts": popular_posts,
        "categories": categories,
        "popular_tags": tags,
    }
    return render(request, "blog/category.html", context)


def tag(request, tag_slug):
    tag_ = Tag.objects.get(slug=tag_slug)
    posts = tag_.posts.filter(featured=True)

    context = {
        "posts": posts,
        "tag": tag_,

        # sidebar
        "popular_posts": popular_posts,
        "categories": categories,
        "popular_tags": tags,
    }
    return render(request, "blog/tag.html", context)


def contact(request):

    # message sent
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Message Sent.")
    else:
        contact_form = CommentForm()

    return render(request, "blog/contact.html")


def about(request):
    context = {
        "popular_posts": popular_posts,
        "popular_tags": tags,
        "categories": categories,
    }
    return render(request, "blog/about.html", context)


def robots(request):
    return render(request, "blog/robots.txt", content_type="text/plain")


def ads(request):
    return render(request, "blog/ads.txt", content_type="text/plain")


# View to handle Search
def search(request):
    if request.GET.get('q'):
        query = request.GET.get('q')
        # query.split() # Todo
        query_list = Post.objects.filter(Q(title__icontains=query), featured=True)   # Note: two underscores
        context = {
            'posts': query_list,
            'query_count': len(query_list),
            'q': query,

            # sidebar
            "popular_posts": popular_posts,
            "categories": categories,
            "popular_tags": tags,
        }
        return render(request, 'blog/search.html', context)
    else:
        return render(request, "blog/search.html", {
            'categories': categories,
        })

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    {% block metas %}

    {% endblock metas %}

	<link rel="shortcut icon" type="image/x-icon" href="{% static 'blog/images/favicon.png' %}">

	<!-- STYLES -->
	<link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/all.min.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/slick.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/simple-line-icons.css' %}" type="text/css" media="all">
	<link rel="stylesheet" href="{% static 'blog/css/style.css' %}" type="text/css" media="all">

	<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- preloader -->
    <div id="preloader">
        <div class="book">
            <div class="inner">
                <div class="left"></div>
                <div class="middle"></div>
                <div class="right"></div>
            </div>
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
    </div>

    <!-- site wrapper -->
    <div class="site-wrapper">

        <div class="main-overlay"></div>

        {% block main %}

        {% endblock main %}

        <!-- instagram feed -->
        {% include "blog/components/instafeed.html" %}

        <!-- footer -->
        {% include "blog/components/footer.html" %}

    </div>
    <!-- end site wrapper -->

    <!-- search popup area -->
    <div class="search-popup">
        <!-- close button -->
        <button type="button" class="btn-close" aria-label="Close"></button>
        <!-- content -->
        <div class="search-content">
            <div class="text-center">
                <h3 class="mb-4 mt-0">Press ESC to close</h3>
            </div>
            <!-- form -->
            <form class="d-flex search-form" method="get" action="{% url 'blog:search' %}">
                <input class="form-control me-2" type="search" name="q" placeholder="Search and press enter ..." aria-label="Search">
                <button class="btn btn-default btn-lg" type="submit"><i class="icon-magnifier"></i></button>
            </form>
        </div>
    </div>

    <!-- canvas menu -->
    <div class="canvas-menu d-flex align-items-end flex-column">
        <!-- close button -->
        <button type="button" class="btn-close" aria-label="Close"></button>

        <!-- logo -->
        <div class="logo">
            <img src="{% static 'blog/images/rc_logo.png' %}" alt="RealCoder" />
        </div>

        <!-- menu -->
        <nav>
            <ul class="vertical-menu">
                <li>
                    <a href="{% url 'blog:index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'blog:category' 'programming' %}">Programming</a>
                </li>
                <li>
                    <a href="{% url 'blog:category' 'crypto' %}">Crypto</a>
                </li>
                <li>
                    <a href="#">Categories</a>
                    <ul class="submenu">
                        {% for cat in categories %}
                        <li><a href="{% url 'blog:category' cat.slug %}">{{ cat.tag }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li>
                    <a href="{% url 'blog:contact' %}">Contact</a>
                </li>
            </ul>
        </nav>

        <!-- social icons -->
        <ul class="social-icons list-unstyled list-inline mb-0 mt-auto w-100">
            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
        </ul>
    </div>

    <!-- JAVA SCRIPTS -->
    <script src="{% static 'blog/js/jquery.min.js' %}"></script>
    <script src="{% static 'blog/js/popper.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/slick.min.js'%}"></script>
    <script src="{% static 'blog/js/jquery.sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'blog/js/custom.js' %}"></script>

    <!-- Alerts/Messages-->
    {% if messages %}	<!-- referring to django messages-->
        {% for message in messages %}
            <script>
              document.addEventListener("DOMContentLoaded", function(){
                alert(" {{ message }}");
              });
            </script>
        {% endfor %}
    {% endif %}
</body>

</html>

blog/templates/blog/category.html
{% extends "blog/base.html" %}
{% load static %}

{% block metas %}
	<title>{{ category.tag }} | RealCoder</title>
	<meta name="description" content="{{ category.meta_description }}">
{% endblock metas %}

{% block main %}

	<!-- header -->
	{% include "blog/components/header.html" %}

    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                <h1 class="mt-0 mb-2">{{ category.tag }}</h1>
<!--                <nav aria-label="breadcrumb">-->
<!--                    <ol class="breadcrumb justify-content-center mb-0">-->
<!--                        <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Home</a></li>-->
<!--                        <li class="breadcrumb-item active" aria-current="page">{{ category.tag }}</li>-->
<!--                    </ol>-->
<!--                </nav>-->
            </div>
        </div>
    </section>

	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">

                    <div class="row gy-4">
                        {% for post in posts%}
                        <div class="col-sm-6">
                            <!-- post -->
                            <div class="post post-grid rounded bordered">
                                <div class="thumb top-rounded">
                                    <a href="{% url 'blog:category' category.slug %}" class="category-badge position-absolute">{{ category.tag }}</a>
                                    <span class="post-format">
                                        <i class="icon-picture"></i>
                                    </span>
                                    <a href="{% url 'blog:detail' post.slug %}">
                                        <div class="inner">
                                            <img src="{{ post.image.url }}" alt="post-title" />
                                        </div>
                                    </a>
                                </div>
                                <div class="details">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item"><a href="{% url 'blog:about' %}"><img src="{% static 'blog/images/rc_logo.png' %}" width="40" class="author" alt="author"/>{{ post.author }}</a></li>
                                        <li class="list-inline-item">{{ post.pub_date|date:"d M Y" }}</li>
                                    </ul>
                                    <h5 class="post-title mb-3 mt-3"><a href="{% url 'blog:detail' post.slug %}">{{ post.title }}</a></h5>
                                    <p class="excerpt mb-0">{{ post.content|truncatechars_html:90|safe }}</p>
                                </div>
                                <div class="post-bottom clearfix d-flex align-items-center">
                                    <div class="social-share me-auto">
                                        <button class="toggle-button icon-share"></button>
                                        <ul class="icons list-unstyled list-inline mb-0">
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="far fa-envelope"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="more-button float-end">
                                        <a href="blog-single.html"><span class="icon-options"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

					<nav>
						<ul class="pagination justify-content-center">
							<li class="page-item active" aria-current="page">
								<span class="page-link">1</span>
							</li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
						</ul>
					</nav>

				</div>

                <!-- sidebar -->
				{% include "blog/components/sidebar.html" %}

			</div>

		</div>
	</section>

{% endblock main %}

blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% load static %}

{% block metas %}
	<title>{{ tag.tag }} | RealCoder</title>
{% endblock metas %}

{% block main %}

	<!-- header -->
	{% include "blog/components/header.html" %}

    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                {% if q %}
                <h1 class="mt-0 mb-2">Search Results for "{{ q }}"</h1>
                {% else %}
                <h1 class="mt-0 mb-2">Search Page"</h1>
                {% endif %}
<!--                <nav aria-label="breadcrumb">-->
<!--                    <ol class="breadcrumb justify-content-center mb-0">-->
<!--                        <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Home</a></li>-->
<!--                        <li class="breadcrumb-item active" aria-current="page">Search Results</li>-->
<!--                    </ol>-->
<!--                </nav>-->
            </div>
        </div>
    </section>

	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">

                    <div class="row gy-4">
                        {% for post in posts%}
                        <div class="col-sm-6">
                            <!-- post -->
                            <div class="post post-grid rounded bordered">
                                <div class="thumb top-rounded">
                                    <a href="{% url 'blog:category' post.category.slug %}" class="category-badge position-absolute">{{ post.category.tag }}</a>
                                    <span class="post-format">
                                        <i class="icon-picture"></i>
                                    </span>
                                    <a href="{% url 'blog:detail' post.slug %}">
                                        <div class="inner">
                                            <img src="{{ post.image.url }}" alt="post-title" />
                                        </div>
                                    </a>
                                </div>
                                <div class="details">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item"><a href="{% url 'blog:about' %}"><img src="{% static 'blog/images/rc_logo.png' %}" width="40" class="author" alt="author"/>{{ post.author }}</a></li>
                                        <li class="list-inline-item">{{ post.pub_date|date:"d M Y" }}</li>
                                    </ul>
                                    <h5 class="post-title mb-3 mt-3"><a href="{% url 'blog:detail' post.slug %}">{{ post.title }}</a></h5>
                                    <p class="excerpt mb-0">{{ post.content|truncatechars_html:90|safe }}</p>
                                </div>
                                <div class="post-bottom clearfix d-flex align-items-center">
                                    <div class="social-share me-auto">
                                        <button class="toggle-button icon-share"></button>
                                        <ul class="icons list-unstyled list-inline mb-0">
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="far fa-envelope"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="more-button float-end">
                                        <a href="blog-single.html"><span class="icon-options"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

					<nav>
						<ul class="pagination justify-content-center">
							<li class="page-item active" aria-current="page">
								<span class="page-link">1</span>
							</li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
						</ul>
					</nav>

				</div>

                <!-- sidebar -->
				{% include "blog/components/sidebar.html" %}

			</div>

		</div>
	</section>

{% endblock main %}

blog/templates/blog/tag.html
{% extends "blog/base.html" %}
{% load static %}

{% block metas %}
	<title>{{ tag.tag }} | RealCoder</title>
{% endblock metas %}

{% block main %}

	<!-- header -->
	{% include "blog/components/header.html" %}

    <section class="page-header">
        <div class="container-xl">
            <div class="text-center">
                <h1 class="mt-0 mb-2">#{{ tag.tag }}</h1>
<!--                <nav aria-label="breadcrumb">-->
<!--                    <ol class="breadcrumb justify-content-center mb-0">-->
<!--                        <li class="breadcrumb-item"><a href="{% url 'blog:index' %}">Home</a></li>-->
<!--                        <li class="breadcrumb-item active" aria-current="page">{{ tag.tag }}</li>-->
<!--                    </ol>-->
<!--                </nav>-->
            </div>
        </div>
    </section>

	<!-- section main content -->
	<section class="main-content">
		<div class="container-xl">

			<div class="row gy-4">

				<div class="col-lg-8">

                    <div class="row gy-4">
                        {% for post in posts%}
                        <div class="col-sm-6">
                            <!-- post -->
                            <div class="post post-grid rounded bordered">
                                <div class="thumb top-rounded">
                                    <a href="{% url 'blog:category' post.category.slug %}" class="category-badge position-absolute">{{ post.category.tag }}</a>
                                    <span class="post-format">
                                        <i class="icon-picture"></i>
                                    </span>
                                    <a href="{% url 'blog:detail' post.slug %}">
                                        <div class="inner">
                                            <img src="{{ post.image.url }}" alt="post-title" />
                                        </div>
                                    </a>
                                </div>
                                <div class="details">
                                    <ul class="meta list-inline mb-0">
                                        <li class="list-inline-item"><a href="{% url 'blog:about' %}"><img src="{% static 'blog/images/rc_logo.png' %}" width="40" class="author" alt="author"/>{{ post.author }}</a></li>
                                        <li class="list-inline-item">{{ post.pub_date|date:"d M Y" }}</li>
                                    </ul>
                                    <h5 class="post-title mb-3 mt-3"><a href="{% url 'blog:detail' post.slug %}">{{ post.title }}</a></h5>
                                    <p class="excerpt mb-0">{{ post.content|truncatechars_html:90|safe }}</p>
                                </div>
                                <div class="post-bottom clearfix d-flex align-items-center">
                                    <div class="social-share me-auto">
                                        <button class="toggle-button icon-share"></button>
                                        <ul class="icons list-unstyled list-inline mb-0">
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="fab fa-telegram-plane"></i></a></li>
                                            <li class="list-inline-item"><a href="#"><i class="far fa-envelope"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="more-button float-end">
                                        <a href="blog-single.html"><span class="icon-options"></span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>

					<nav>
						<ul class="pagination justify-content-center">
							<li class="page-item active" aria-current="page">
								<span class="page-link">1</span>
							</li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
						</ul>
					</nav>

				</div>

                <!-- sidebar -->
				{% include "blog/components/sidebar.html" %}

			</div>

		</div>
	</section>

{% endblock main %}