blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="index"),
    path("post/<slug:post_slug>/", views.detail, name="detail"),
    path("category/<slug:cat_slug>/", views.category, name="category"),
    path("tag/<slug:tag_slug>/", views.tag, name="tag"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("search/", views.search, name="search"),

    path("robots.txt", views.robots, name="robots"),
    path("ads.txt", views.ads, name="ads"),
]

marketing/urls.py
from django.urls import path
from . import views


app_name = "marketing"
urlpatterns= [
    path("subscribe/", views.subscribe, name="subscribe"),
]

realcoder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap, StaticViewSitemap, CategorySitemap


sitemaps = {
    'static': StaticViewSitemap,
    'post': PostSitemap,
    'category': CategorySitemap,
}

urlpatterns = [
    path("", include("blog.urls")),
    path('admin/', admin.site.urls),
    path("email-list/", include("marketing.urls")),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemaps'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone


# Author model
class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"


# Category model
class Category(models.Model):
    tag = models.CharField(max_length=50, unique=True)
    slug = models.SlugField()
    meta_description = models.TextField(max_length=170, blank=True)

    def __str__(self):
        return f'{self.tag}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:category', args=[str(self.slug)])


class Tag(models.Model):
    tag = models.CharField(max_length=50, unique=True)
    slug = models.SlugField()
    popular = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.tag}'

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:tag', args=[str(self.slug)])


# Post model
class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='post_images', blank=True)
    meta_description = models.TextField(max_length=170, blank=True)
    content = RichTextUploadingField()
    pub_date = models.DateTimeField(default=timezone.now)      # default=timezone.now - from django.utils import tim...
    category = models.ForeignKey(Category, related_name='posts', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, related_name="posts")
    featured = models.BooleanField(default=False)
    popular = models.BooleanField(default=False)


    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:detail', args=[str(self.slug)])


# Comment model
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=99)
    email = models.EmailField()
    comment = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"Comment on ''{self.post}'' by {self.name}"


# Comment Reply
class ReplyComment(models.Model):
    name = models.ForeignKey(Author, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies", blank=False)
    reply_message = models.TextField(blank=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f"Reply: {self.reply_message}"


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(blank=False)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message: {self.name} - {self.message[:150]}..."

blog/forms.py
from django import forms
from .models import Comment, Contact


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', 'name', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message')

blog/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q
from .forms import *
from django.contrib import messages
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage


# Create your views here.

# global stuff
popular_posts = Post.objects.filter(popular=True, featured=True)
categories = Category.objects.all()
tags = Tag.objects.filter(popular=True)


def index(request):
    posts = Post.objects.filter(featured=True)

    # Pagination - My most impressive implementation
    paginator = Paginator(posts, 3)
    num_pages = [i for i in range(1, paginator.num_pages)]
    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer, deliver the first page
        post_list = paginator.page(1)
    except EmptyPage:
        # if page is out of range, deliver last page of results
        post_list = paginator.page(paginator.num_pages)

    context = {
        "posts": post_list,
        "num_pages": num_pages,

        "popular_tags": tags,
        "popular_posts": popular_posts,
        "categories": categories,
    }
    return render(request, "blog/index.html", context)


def detail(request, post_slug):
    post = Post.objects.get(slug=post_slug)
    comments = post.comments.filter(active=True)
    post_tags = post.tags.all()

    new_comment = None
    # comment posted
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            # Create a comment but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
            messages.success(request, "Your comment is awaiting moderation.")
    else:
        comment_form = CommentForm()


    context = {
        "post": post,
        "comments": comments,
        "post_tags": post_tags,
        "new_comment": new_comment,
        # sidebars
        "categories": categories,
        "popular_posts": popular_posts,
        "popular_tags": tags,
    }
    return render(request, "blog/detail.html", context)


def category(request, cat_slug):
    cat = Category.objects.get(slug=cat_slug)
    posts = cat.posts.filter(featured=True)

    context = {
        "posts": posts,
        "category": cat,

        # sidebar
        "popular_posts": popular_posts,
        "categories": categories,
        "popular_tags": tags,
    }
    return render(request, "blog/category.html", context)


def tag(request, tag_slug):
    tag_ = Tag.objects.get(slug=tag_slug)
    posts = tag_.posts.filter(featured=True)

    context = {
        "posts": posts,
        "tag": tag_,

        # sidebar
        "popular_posts": popular_posts,
        "categories": categories,
        "popular_tags": tags,
    }
    return render(request, "blog/tag.html", context)


def contact(request):

    # message sent
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Message Sent.")
    else:
        contact_form = CommentForm()

    return render(request, "blog/contact.html")


def about(request):
    context = {
        "popular_posts": popular_posts,
        "popular_tags": tags,
        "categories": categories,
    }
    return render(request, "blog/about.html", context)


def robots(request):
    return render(request, "blog/robots.txt", content_type="text/plain")


def ads(request):
    return render(request, "blog/ads.txt", content_type="text/plain")


# View to handle Search
def search(request):
    if request.GET.get('q'):
        query = request.GET.get('q')
        # query.split() # Todo
        query_list = Post.objects.filter(Q(title__icontains=query), featured=True)   # Note: two underscores
        context = {
            'posts': query_list,
            'query_count': len(query_list),
            'q': query,

            # sidebar
            "popular_posts": popular_posts,
            "categories": categories,
            "popular_tags": tags,
        }
        return render(request, 'blog/search.html', context)
    else:
        return render(request, "blog/search.html", {
            'categories': categories,
        })

blog/templates/blog/components/footer.html
<footer>
            <div class="container-xl">
                <div class="footer-inner">
                    <div class="row d-flex align-items-center gy-4">
                        <!-- copyright text -->
                        <div class="col-md-4">
                            <span class="copyright">© 2021 RealCoder.</span>
                        </div>

                        <!-- social icons -->
                        <div class="col-md-4 text-center">
                            <ul class="social-icons list-unstyled list-inline mb-0">
                                <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                                <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                            </ul>
                        </div>

                        <!-- go to top button -->
                        <div class="col-md-4">
                            <a href="#" id="return-to-top" class="float-md-end"><i class="icon-arrow-up"></i>Back to Top</a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

blog/templates/blog/components/header-default.html
{% load static %}
<header class="header-default">
		<nav class="navbar navbar-expand-lg">
			<div class="container-xl">
				<!-- site logo -->
				<a class="navbar-brand" href="{% url 'blog:index' %}"><img src="{% static 'blog/images/rc_logo.png' %}" alt="logo" width="80" /></a>

				<div class="collapse navbar-collapse">
					<!-- menus -->
					<ul class="navbar-nav mr-auto">
						{% include "blog/components/nav-list.html" %}
					</ul>
				</div>

				<!-- header right section -->
				<div class="header-right">
					<!-- social icons -->
					<ul class="social-icons list-unstyled list-inline mb-0">
						<li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
						<li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
					</ul>
					<!-- header buttons -->
					<div class="header-buttons">
						<button class="search icon-button">
							<i class="icon-magnifier"></i>
						</button>
						<button class="burger-menu icon-button d-lg-none">
							<span class="burger-icon"></span>
						</button>
					</div>
				</div>
			</div>
		</nav>
	</header>

blog/templates/blog/components/header.html
{% load static %}
<header class="header-personal">
        <div class="container-xl header-top">
            <div class="row align-items-center">

                <div class="col-4 d-none d-md-block d-lg-block">
                    <!-- social icons -->
                    <ul class="social-icons list-unstyled list-inline mb-0">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                    </ul>
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 text-center">
                <!-- site logo -->
                    <a class="navbar-brand" href="{% url 'blog:index' %}"><img src="{% static 'blog/images/rc_logo.png' %}" width="150" alt="logo" /></a>
                    <a href="{% url 'blog:index' %}" class="d-block text-logo">RealCoder<span class="dot">.</span></a>
                    <span class="slogan d-block">Interesting Tech Content and Articles for Geeks.</span>
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12">
                    <!-- header buttons -->
                    <div class="header-buttons float-md-end mt-4 mt-md-0">
                        <button class="search icon-button">
                            <i class="icon-magnifier"></i>
                        </button>
                        <button class="burger-menu icon-button ms-2 float-end float-md-none d-lg-none">
                            <span class="burger-icon"></span>
                        </button>
                    </div>
                </div>

            </div>
        </div>

        <nav class="navbar navbar-expand-lg">
            <div class="container-xl">

                <div class="collapse navbar-collapse justify-content-center centered-nav">
                    <!-- menus -->
                    <ul class="navbar-nav">
                        {% include "blog/components/nav-list.html" %}
                    </ul>
                </div>

            </div>
        </nav>
    </header>

blog/templates/blog/components/instafeed.html
{% load static %}
<div class="instagram">
            <div class="container-xl">
                <!-- images -->
                <div class="instagram-feed d-flex flex-wrap text-center">
                    <div class="col-12">
                        <a href="https://click.linksynergy.com/fs-bin/click?id=w7*S3fGR7tg&offerid=507388.1539&subid=0&type=4" target="_blank">
                            <img src="{% static 'blog/images/ads/udemy_wide_banner.png' %}">
                        </a>
                    </div>
            </div>
        </div>

blog/templates/blog/components/nav-list.html
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:category' 'programming' %}">Programming</a>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:category' 'crypto' %}">Crypto</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#">Categories</a>
    <ul class="dropdown-menu">
        {% for cat in categories %}
        <li><a class="dropdown-item" href="{% url 'blog:category' cat.slug %}">{{ cat.tag }}</a></li>
        {% endfor %}
    </ul>
</li>
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
</li>

blog/templates/blog/components/sidebar.html
{% load static %}

<div class="col-lg-4">

    <!-- sidebar -->
    <div class="sidebar">
        <!-- widget about -->
        <div class="widget rounded">
            <div class="widget-about data-bg-image text-center" data-bg-image="{% static 'blog/images/map-bg.png' %}">
                <p href="personal.html" class="d-block text-logo">RealCoder<span class="dot">.</span></p>
                <p class="mb-4">Hello, We’re content writer who is fascinated by content fashion, celebrity and lifestyle. We helps clients bring the right content to the right people.</p>
                <ul class="social-icons list-unstyled list-inline mb-0">
                    <li class="list-inline-item"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-twitter"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-medium"></i></a></li>
                    <li class="list-inline-item"><a href="#"><i class="fab fa-youtube"></i></a></li>
                </ul>
            </div>
        </div>

        <!-- widget popular posts -->
        <div class="widget rounded">
            <div class="widget-header text-center">
                <h3 class="widget-title">Popular Posts</h3>
                <img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
            </div>
            <div class="widget-content">
                {% for p_post in popular_posts %}
                <!-- post -->
                <div class="post post-list-sm circle">
                    <div class="thumb circle">
                        <span class="number">{{ forloop.counter }}</span>
                        <a href="blog-single.html">
                            <div class="inner">
                                <img src="{{ p_post.image.url }}" alt="post-title" />
                            </div>
                        </a>
                    </div>
                    <div class="details clearfix">
                        <h6 class="post-title my-0"><a href="blog-single.html">{{ p_post.title }}}</a></h6>
                        <ul class="meta list-inline mt-1 mb-0">
                            <li class="list-inline-item">{{ p_post.pub_date|date:"d M Y" }}</li>
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <!-- widget categories -->
        <div class="widget rounded">
            <div class="widget-header text-center">
                <h3 class="widget-title">Explore Topics</h3>
                <img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
            </div>
            <div class="widget-content">
                <ul class="list">
                    {% for cat in categories %}
                    <li><a href="{% url 'blog:category' cat.slug %}">{{ cat.tag }}</a><span>({{ cat.posts.all|length }})</span></li>
                    {% endfor %}
                </ul>
            </div>

        </div>

        <!-- widget newsletter -->
        <div class="widget rounded">
            <div class="widget-header text-center">
                <h3 class="widget-title">Newsletter</h3>
                <img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
            </div>
            <div class="widget-content">
                <span class="newsletter-headline text-center mb-3">Join 70,000 subscribers!</span>
                <form method="post" action="{% url 'marketing:subscribe' %}">
                    {% csrf_token%}
                    <div class="mb-2">
                        <input class="form-control w-100 text-center" name=email placeholder="Email address…" type="email">
                    </div>
                    <button class="btn btn-default btn-full" type="submit">Sign Up</button>
                </form>
                <span class="newsletter-privacy text-center mt-3">By signing up, you agree to our <a href="#">Privacy Policy</a></span>
            </div>
        </div>

        <!-- widget post carousel -->
        <div class="widget rounded">
            <div class="widget-header text-center">
                <h3 class="widget-title">Celebration</h3>
                <img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
            </div>
            <div class="widget-content">
                <div class="post-carousel-widget">
                    {% for p_post in popular_posts %}
                    <!-- post -->
                    <div class="post post-carousel">
                        <div class="thumb rounded">
                            <a href="category.html" class="category-badge position-absolute">How to</a>
                            <a href="blog-single.html">
                                <div class="inner">
                                    <img src="{{ p_post.image.url }}" alt="post-title" />
                                </div>
                            </a>
                        </div>
                        <h5 class="post-title mb-0 mt-4"><a href="blog-single.html">{{ p_post.title }}</a></h5>
                        <ul class="meta list-inline mt-2 mb-0">
                            <li class="list-inline-item"><a href="#">{{ p_post.author }}</a></li>
                            <li class="list-inline-item">{{ p_post.pub_date|date:"d M Y" }}</li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
                <!-- carousel arrows -->
                <div class="slick-arrows-bot">
                    <button type="button" data-role="none" class="carousel-botNav-prev slick-custom-buttons" aria-label="Previous"><i class="icon-arrow-left"></i></button>
                    <button type="button" data-role="none" class="carousel-botNav-next slick-custom-buttons" aria-label="Next"><i class="icon-arrow-right"></i></button>
                </div>
            </div>
        </div>

        <!-- widget advertisement -->
        <div class="widget no-container rounded text-md-center">
            <span class="ads-title">- Sponsored Ad -</span>
            <a href="https://click.linksynergy.com/fs-bin/click?id=w7*S3fGR7tg&offerid=507388.18492&subid=0&type=4" class="widget-ads">
                <img src="{% static 'blog/images/ads/udemy-min.png' %}" alt="Advertisement" />
            </a>
        </div>

        <!-- widget tags -->
        <div class="widget rounded">
            <div class="widget-header text-center">
                <h3 class="widget-title">Tag Clouds</h3>
                <img src="{% static 'blog/images/wave.svg' %}" class="wave" alt="wave" />
            </div>
            <div class="widget-content">
                {% for tag in popular_tags %}
                <a href="#" class="tag">#{{ tag.tag }}</a>
                {% endfor %}
            </div>
        </div>

    </div>

</div>